/**
 * cosmoAssets.ts — manifest for every COSMO sprite (src/assets/cosmo/*.png).
 *
 * The artwork was extracted frame-by-frame, so every pose ships on its own
 * canvas size with different amounts of baked-in effect art (thruster trails,
 * music notes, cursor icons, thought text). The sprite engine uses this
 * manifest to normalize rendering:
 *
 *   w/h    — canvas size in pixels
 *   ax/ay  — anchor point INSIDE the canvas, as a fraction of its size.
 *            ax pins the character's body centre-x, ay pins the ground
 *            (feet / thruster) line. The engine pins (ax·w, ay·h) of every
 *            pose to the same screen point, so switching poses never makes
 *            the character jump, and wide effect art stays balanced.
 *   corr   — extra scale correction for poses whose canvas includes effect
 *            art above/below the body (pads, auras, Zzz, hands). 1 = the
 *            canvas height IS the character height.
 *   facing — which way the artwork natively faces. The travel system uses
 *            this to pick art instead of mirroring whatever it has.
 *   effect — pure VFX art (never displayed as the character itself).
 *
 * Generated by measuring the PNGs directly; update if assets change.
 */

export type CosmoFacing = 'left' | 'right' | 'front' | 'back';

export interface CosmoAsset {
  w: number;
  h: number;
  ax: number;
  ay: number;
  corr?: number;
  facing?: CosmoFacing;
  effect?: boolean;
}

export const COSMO_ASSETS: Record<string, CosmoAsset> = {
  /* hero orientations ------------------------------------------------ */
  back: { w: 112, h: 126, ax: 0.5, ay: 1, facing: 'back' },
  front: { w: 103, h: 126, ax: 0.5, ay: 1, facing: 'front' },
  left: { w: 106, h: 126, ax: 0.5, ay: 1, facing: 'left' },
  right: { w: 102, h: 126, ax: 0.5, ay: 1, facing: 'right' },

  /* flight cycle (artwork faces right; mirrored for leftward travel) -- */
  'fly-1': { w: 120, h: 74, ax: 0.72, ay: 1, facing: 'right' },
  'fly-2': { w: 74, h: 73, ax: 0.62, ay: 1, facing: 'right' },
  'fly-3': { w: 77, h: 72, ax: 0.6, ay: 1, facing: 'right' },
  'fly-4': { w: 75, h: 71, ax: 0.62, ay: 1, facing: 'right' },
  dash: { w: 69, h: 55, ax: 0.62, ay: 1, facing: 'right' },
  'take-off': { w: 59, h: 72, ax: 0.5, ay: 1, facing: 'right' },
  land: { w: 59, h: 71, ax: 0.5, ay: 1, facing: 'front' },
  'turn-mid-air': { w: 74, h: 74, ax: 0.5, ay: 1, facing: 'right' },
  drift: { w: 66, h: 73, ax: 0.55, ay: 1, facing: 'right' },
  trail: { w: 126, h: 61, ax: 0.5, ay: 1, effect: true },

  /* idle & micro-actions ---------------------------------------------- */
  'idle-1': { w: 46, h: 54, ax: 0.5, ay: 1 },
  'idle-2': { w: 46, h: 54, ax: 0.5, ay: 1 },
  blink: { w: 54, h: 55, ax: 0.5, ay: 1 },
  float: { w: 61, h: 50, ax: 0.5, ay: 1 },
  'hover-mid': { w: 68, h: 58, ax: 0.5, ay: 1 },
  'hover-high': { w: 49, h: 56, ax: 0.5, ay: 1 },
  sit: { w: 60, h: 41, ax: 0.5, ay: 1, corr: 0.62 },
  nod: { w: 62, h: 45, ax: 0.5, ay: 1 },
  wave: { w: 45, h: 56, ax: 0.5, ay: 1 },
  salute: { w: 51, h: 54, ax: 0.5, ay: 1 },
  point: { w: 72, h: 54, ax: 0.42, ay: 1 },
  stop: { w: 48, h: 73, ax: 0.5, ay: 1 },
  disappointed: { w: 50, h: 47, ax: 0.5, ay: 1, corr: 0.9 },
  drop: { w: 47, h: 49, ax: 0.5, ay: 1, corr: 0.95 },

  /* looking ------------------------------------------------------------- */
  'look-up': { w: 50, h: 55, ax: 0.5, ay: 1 },
  'look-down': { w: 51, h: 56, ax: 0.5, ay: 1 },
  'look-left': { w: 58, h: 53, ax: 0.5, ay: 1 },
  'look-right': { w: 47, h: 53, ax: 0.5, ay: 1 },

  /* cursor interaction -------------------------------------------------- */
  /* (baked-in cursor/hand art was scrubbed from these frames — the real
     cursor is never part of the sprite) */
  'cursor-nearby': { w: 59, h: 49, ax: 0.33, ay: 1, corr: 0.95 },
  'follow-cursor': { w: 69, h: 56, ax: 0.45, ay: 1, corr: 0.95 },
  'push-back': { w: 73, h: 54, ax: 0.28, ay: 1, corr: 0.92 },
  'drag-start': { w: 62, h: 56, ax: 0.35, ay: 1, corr: 0.95 },
  dragging: { w: 70, h: 56, ax: 0.38, ay: 1, corr: 0.95 },

  /* states & reactions --------------------------------------------------- */
  thinking: { w: 68, h: 67, ax: 0.5, ay: 1 },
  confused: { w: 78, h: 70, ax: 0.45, ay: 1 },
  excited: { w: 78, h: 70, ax: 0.5, ay: 1 },
  celebration: { w: 87, h: 70, ax: 0.5, ay: 1 },
  sleeping: { w: 78, h: 70, ax: 0.5, ay: 1, corr: 0.78 },
  waking: { w: 69, h: 67, ax: 0.45, ay: 1 },
  charging: { w: 71, h: 70, ax: 0.5, ay: 1, corr: 0.88 },

  /* music ---------------------------------------------------------------- */
  listening: { w: 70, h: 70, ax: 0.5, ay: 1 },
  dancing: { w: 104, h: 70, ax: 0.5, ay: 1 },

  /* work ------------------------------------------------------------------ */
  typing: { w: 98, h: 70, ax: 0.42, ay: 1 },
};
